name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Stop and remove old containers with prefix tscoolbot-
        run: docker container ls --filter name="tscoolbot-.*" -aq | xargs -r docker rm -f

      - name: Remove old Docker images with prefix tscoolbot-
        run: docker images --filter reference="tscoolbot-.*" -q | xargs -r docker rmi -f

  build:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t tscoolbot-${{ github.run_number }} .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run Docker container with secret
        env:
          TELEGRAF_BOT_TOKEN: ${{ secrets.TELEGRAF_BOT_TOKEN }}
          LINK_SHORTENER_URL: ${{ vars.LINK_SHORTENER_URL }}
        run: |
          docker run \
            -d \
            -e TELEGRAF_BOT_TOKEN="$TELEGRAF_BOT_TOKEN" \
            -e LINK_SHORTENER_URL="$LINK_SHORTENER_URL" \
            --name tscoolbot-${{ github.run_number }} \
            tscoolbot-${{ github.run_number }}
