name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove old container with prefix tscoolbot-
        run: docker container ls --filter name="tscoolbot-.*" -aq | xargs -r docker rm -f

      - name: Remove old Docker images with prefix tscoolbot-
        run: docker images --filter name="tscoolbot-.*" -aq | xargs -r docker rmi -f

      - name: Build Docker image
        run: docker build -t tscoolbot-${{ github.run_number }} .

      - name: Run Docker container with secret
        env:
          TELEGRAF_BOT_TOKEN: ${{ secrets.TELEGRAF_BOT_TOKEN }}
          LINK_SHORTENER_URL: ${{ vars.LINK_SHORTENER_URL }}
        run: |
          docker run \
            -d \
            -e TELEGRAF_BOT_TOKEN="$TELEGRAF_BOT_TOKEN" \
            -e LINK_SHORTENER_URL="$LINK_SHORTENER_URL" \
            --name tscoolbot-${{ github.run_number }} \
            tscoolbot-${{ github.run_number }}
