name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Запускать при пуше в основную ветку

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Клонируем репозиторий

      - name: Stop and remove old container with prefix tscoolbot-
        run: docker ps -q --filter "name=tscoolbot-" | xargs -r docker stop | xargs -r docker rm

      - name: Remove old Docker images with prefix tscoolbot-
        run: docker images --filter=reference='tscoolbot-*' -q | xargs -r docker rmi

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2  # Устанавливаем Docker Buildx для кросс-платформенной сборки

      - name: Build Docker image
        run: docker build -t tscoolbot-${{ github.run }} .

      - name: Run Docker container with secret
        run: docker run -e TELEGRAF_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}' -e LINK_SHORTENER_URL='${{ env.LINK_SHORTENER_URL }}' --name tscoolbot-${{ github.run }} tscoolbot-${{ github.run }}
